# Runs a sample mongodb service
version: "3"
services:

  gamelist-server:
    restart: unless-stopped
    networks:
      - gamelist-net
    ports:
      - 80:10555
    volumes:
      # Data is used path within docker container
      - ./target:/data

  # mongo:
  #   restart: unless-stopped
  #   networks:
  #     - gamelist-net
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo-db:/data/db
  #   image: "mongo:latest"

  # mongo-express:
  #   restart: unless-stopped
  #   networks:
  #     - gamelist-net
  #   ports:
  #     - 8081:8081
  #   image: "mongo-express:latest"
  #   ports:
  #       - 8081:8081

networks:
  gamelist-net:
    driver: bridge
